(function () {
  "use strict";

  window.LeerpretArchitectLanguages = {
    defaultLanguage: "nl",
    messages: {
      nl: {
        "app.title": "Leerpretarchitect Editor",
        "brand.kicker": "Leerpretarchitect",
        "app.heading": "Leerbox-editor",
        "actions.new": "Nieuw",
        "actions.uploadDescription": "Upload",
        "actions.prompt": "AI-prompt",
        "actions.downloadPrompt": "Download prompt",
        "actions.import": "Importeer JSON",
        "actions.simulate": "Simuleer Leerpret",
        "actions.export": "Exporteer JSON",
        "actions.copy": "Kopieer",
        "actions.copied": "Gekopieerd",
        "actions.close": "Sluiten",
        "actions.object": "Object",
        "actions.step": "Stap",
        "actions.dependency": "Voorwaarde",
        "actions.delete": "Verwijder",
        "actions.cancel": "Annuleer",
        "actions.save": "Bewaar",
        "language.label": "Taal",
        "language.nl": "Nederlands",
        "tabs.overview": "Kern",
        "tabs.design": "Ontwerp",
        "tabs.game": "Game",
        "tabs.entry": "Start",
        "tabs.play": "Spel",
        "tabs.sequence": "Route",
        "tabs.measurement": "Meten",
        "aria.fileActions": "Bestandsacties",
        "aria.editor": "Leerbox editor",
        "aria.intake": "Intakevelden",
        "aria.tabs": "Editor onderdelen",
        "aria.workspace": "Visuele programmeerwerkplaats",
        "aria.audit": "Capture-audit",
        "aria.jsonExport": "JSON export",
        "aria.jsonOutput": "JSON uitvoer",
        "aria.close": "Sluiten",
        "workspace.kicker": "Visuele bouwblokken",
        "workspace.newTitle": "Nieuwe leerbox",
        "lanes.objects": "Objecten",
        "lanes.route": "Interactieroute",
        "lanes.dependencies": "Afhankelijkheden",
        "audit.requiredComplete": "verplichte velden compleet",
        "audit.ready": "klaar voor capture-export",
        "audit.openQuestion": "Nog invullen: {item}",
        "json.kicker": "Capture JSON",
        "json.heading": "Live uitvoer",
        "labels.name": "Naam",
        "labels.leerboxId": "Leerbox-id",
        "labels.mode": "Modus",
        "labels.type": "Type",
        "labels.status": "Status",
        "labels.socialSetting": "Sociale setting",
        "labels.domain": "Domein",
        "labels.summary": "Samenvatting",
        "labels.learningGoal": "Leerdoel",
        "labels.successDefinition": "Succesdefinitie",
        "labels.targetGroup": "Doelgroep",
        "labels.firstVisibleAction": "Eerste zichtbare actie",
        "labels.minimalStartInstruction": "Minimale startinstructie",
        "labels.selfStartingSignal": "Self-starting signaal",
        "labels.selfExplainingCues": "Self-explaining cues",
        "labels.proactiveInvitation": "Proactieve uitnodiging",
        "labels.playForm": "Herkenbare spelvorm",
        "labels.theme": "Thema of verhaal",
        "labels.coreMechanics": "Kernmechanieken",
        "labels.rules": "Regels of beperkingen",
        "labels.freedomDegrees": "Vrijheidsgraden",
        "labels.feedbackLoop": "Directe feedbacklus",
        "labels.routeModel": "Routemodel",
        "labels.freedomPrinciple": "Vrijheidsprincipe",
        "labels.preferredRoute": "Voorkeursroute",
        "labels.freeChoiceZones": "Vrije keuzezones",
        "labels.forcedPathRisk": "Risico op gedwongen pad",
        "labels.variationOpportunities": "Variatiekansen",
        "labels.mainBarrier": "Hoofdbarriere",
        "labels.actionTypes": "Action types",
        "labels.resultValues": "Result values",
        "labels.notVisibleToEngine": "Niet zichtbaar voor engine",
        "labels.realismNotes": "Realismenotities contactgeneratie",
        "labels.privacy": "Privacy",
        "labels.attractionType": "Type leerattractie",
        "labels.learningModes": "Leerwijzen",
        "labels.leerboxPrinciples": "Leerbox-principes",
        "labels.materialMix": "Materiaalmix",
        "labels.boxClimates": "Boxklimaten",
        "labels.goodPractices": "Good practices",
        "labels.gameGenres": "Gamegenres",
        "labels.playerGoal": "Spelersdoel",
        "labels.winState": "Winconditie",
        "labels.failState": "Faalconditie",
        "labels.rulesSummary": "Regels",
        "labels.gameMechanics": "Mechanics",
        "labels.gameDynamics": "Dynamics",
        "labels.gameAesthetics": "Aesthetics / speelervaring",
        "labels.progression": "Progressie",
        "labels.coreLoops": "Core loops",
        "labels.challengeCurve": "Challenge curve",
        "labels.onboarding": "Onboarding",
        "placeholders.autoKebab": "wordt automatisch kebab-case",
        "required.name": "naam",
        "required.type": "type",
        "required.status": "status",
        "required.learningGoal": "leerdoel",
        "required.successDefinition": "succesdefinitie",
        "required.targetGroup": "doelgroep",
        "required.firstAction": "eerste actie",
        "required.selfStarting": "self-starting",
        "required.initiative": "initiatief",
        "required.playForm": "spelvorm",
        "required.freedomDegrees": "vrijheidsgraden",
        "required.routeModel": "routemodel",
        "required.barrier": "barriere",
        "required.object": "minimaal 1 object",
        "required.step": "minimaal 1 stap",
        "required.layers": "laagscheiding",
        "empty.object": "Voeg leerobjecten toe: fysieke spullen, schermen, rollen, feedbackmomenten of succesobjecten.",
        "empty.step": "Bouw de route als stapblokken. Dat mag een vrije of voorkeursroute zijn, niet alleen een vaste methode.",
        "empty.dependency": "Leg hier harde locks vast: wat is pas beschikbaar na een eerder contact?",
        "block.newObject": "Nieuw leerobject",
        "block.noAffordance": "Geen affordance ingevuld",
        "block.newStep": "Nieuwe routestap",
        "block.noFeedback": "Geen feedback ingevuld",
        "block.noReason": "Geen reden ingevuld",
        "dialog.object": "Leerobject",
        "dialog.step": "Routestap",
        "dialog.dependency": "Voorwaarde",
        "dialog.new": "Nieuw",
        "dialog.edit": "Bewerk",
        "dialog.objectId": "Object-id",
        "objectref.choose": "Kies een leerobject…",
        "objectref.missing": "bestaat niet meer",
        "dialog.label": "Label",
        "dialog.role": "Rol",
        "dialog.objectType": "Objecttype",
        "dialog.materialCategory": "Materiaalcategorie",
        "dialog.affordance": "Affordance",
        "dialog.feedbackType": "Feedbacktype",
        "dialog.barrierType": "Barrieretype",
        "dialog.sensorModality": "Sensoriek",
        "dialog.visibleCues": "Zichtbare cues",
        "dialog.loggableActions": "Logbare acties",
        "dialog.accessConditions": "Toegangsvoorwaarden",
        "dialog.likelyMarkerRoles": "Waarschijnlijke markerrollen",
        "dialog.learningModeTags": "Leerwijzen",
        "dialog.goodPracticeTags": "Good practices",
        "dialog.participantAction": "Deelnemeractie",
        "dialog.actionType": "Action type",
        "dialog.gameMechanic": "Game mechanic",
        "dialog.gameDynamic": "Game dynamic",
        "dialog.expectedFeedback": "Verwachte feedback",
        "dialog.ifSuccess": "Bij succes",
        "dialog.ifStuck": "Bij vastlopen",
        "dialog.fromObject": "Van object-id",
        "dialog.toObject": "Naar object-id",
        "dialog.type": "Type",
        "dialog.reason": "Reden",
        "confirm.reset": "Nieuwe lege capture starten? Niet-geexporteerde wijzigingen verdwijnen uit deze browser-editor.",
        "alert.importFailed": "Dit JSON-bestand kon niet als leerbox-capture worden gelezen.",
        "export.defaultFile": "leerbox-capture",
        "prompt.title": "Start vanuit beschrijving",
        "prompt.help": "Kopieer deze prompt naar een LLM, plak daaronder je menselijke beschrijving en importeer daarna de JSON die eruit komt.",
        "prompt.copy": "Kopieer prompt",
        "prompt.copied": "Prompt gekopieerd",
        "prompt.descriptionPlaceholder": "[PLAK HIER JE MENSELIJKE BESCHRIJVING VAN DE LEERARCHITECTUUR]",
        "prompt.text": "Je bent geen mede-ontwerper en geen adviseur. Je bent een intake-analist en registratie-assistent voor leerarchitectuur.\n\nDoel: maak van mijn menselijke beschrijving een uniform leerbox_capture_v5 JSON-bestand dat ik kan importeren in de Leerpretarchitect editor.\n\nBelangrijke grenzen:\n1. Doe geen ontwerpsuggesties.\n2. Doe geen verbetervoorstellen.\n3. Geef geen simulatiescores, leerpretscores of marktpotentie.\n4. Vul ontbrekende inhoud niet creatief in.\n5. Als iets onbekend blijft, noteer exact \"unknown\".\n6. Gebruik lege lijsten [] als er geen items bekend zijn.\n7. Gebruik voor statusvelden alleen \"present\", \"partial\", \"absent\" of \"unknown\".\n8. Behoud alle JSON-sleutels en enumwaarden in het Engels.\n9. Normaliseer leerbox_id naar kebab-case en object_id naar snake_case.\n10. Gebruik alleen de termen computertaal-statements of syntaxis voor de formele statements.\n\nOnderbouwing syntaxis: Deze specifieke trefwoorden en syntaxisdefinities zijn gekozen op basis van eerdere praktijkvalidatie, omdat ze patronen van vrije actieregulatie consistent vangen in leermetadata.\n\nRegistreer expliciet: self-starting, self-explaining, proactieve uitnodiging, speelkader, regels, vrijheid, volgorde, afhankelijkheden, herhaling, feedback, objecten, minimale contactberichten, rijke simulatorcontext, archetypeverwachtingen en game design inclusief spelersdoel, win state, fail state, mechanics, dynamics, aesthetics, resources, progressie, core loops, onboarding en balancing.\n\nMaak daarnaast twee extra representaties in hetzelfde JSON-object:\n- fallback_latex_description: een professioneel aangescherpte beschrijving in LaTeX, in de stijl en woordkeuze van de gebruiker.\n- computertaal_statements: full_architecture en captured_learning_box, waarbij captured_learning_box alleen de objecten, typen, afhankelijkheden en minimale engine-relevante velden bevat.\n\nLaagscheiding: de simulator en ontwerpaudit mogen rijke context gebruiken; de leerpret-engine krijgt later alleen minimale informatiearme contactberichten en mag de rijke leerboxdefinitie niet als voorkennis gebruiken.\n\nGeef alleen geldig JSON terug. Gebruik geen markdown code fences en geen uitleg voor of na het JSON-object.\n\nGebruik deze JSON-structuur als uitgangspunt:\n{schema}\n\nMenselijke beschrijving:\n{description}",
        "enum.unknown": "onbekend",
        "enum.existing": "bestaand",
        "enum.desired": "gewenst",
        "enum.mixed": "gemengd",
        "enum.physical": "fysiek",
        "enum.digital": "digitaal",
        "enum.hybrid": "hybride",
        "enum.role_simulation": "rollensimulatie",
        "enum.idea": "idee",
        "enum.existing_practice": "bestaande praktijk",
        "enum.proto_leerbox": "proto-leerbox",
        "enum.pilot": "pilot",
        "enum.digital_twin": "digital twin",
        "enum.validated": "gevalideerd",
        "enum.individual": "individueel",
        "enum.pair": "tweetal",
        "enum.group": "groep",
        "enum.free": "vrij",
        "enum.preferred_sequence": "voorkeursvolgorde",
        "enum.partly_locked": "deels vergrendeld",
        "enum.fixed_sequence": "vaste volgorde",
        "enum.start": "start",
        "enum.entry": "begin",
        "enum.orientation": "orientatie",
        "enum.mission": "missie",
        "enum.rule": "regel",
        "enum.story": "verhaal",
        "enum.exploration": "verkenning",
        "enum.practice": "oefening",
        "enum.variation": "variatie",
        "enum.barrier": "barriere",
        "enum.resistance": "weerstand",
        "enum.recovery": "herstel",
        "enum.feedback": "feedback",
        "enum.progress": "voortgang",
        "enum.reward": "beloning",
        "enum.success": "succes",
        "enum.exit": "eind",
        "enum.social": "sociaal",
        "enum.role_token": "roltoken",
        "enum.must_complete": "moet afronden",
        "enum.must_visit": "moet bezoeken",
        "enum.must_choose": "moet kiezen",
        "enum.safety_lock": "veiligheidslock",
        "enum.role_lock": "rollock",
        "enum.presenting": "presenterend",
        "enum.applying": "toepassend",
        "enum.investigating": "onderzoekend",
        "enum.creating": "creerend",
        "enum.reproductive": "reproductief",
        "enum.application_oriented": "toepassingsgericht",
        "enum.meaning_oriented": "betekenisgericht",
        "enum.productive": "productief",
        "enum.investigative": "onderzoekend",
        "enum.design_based": "ontwerpend",
        "enum.entrepreneurial": "ondernemend",
        "enum.playful": "speels",
        "enum.visual": "beeldend",
        "enum.narrative": "verhalend",
        "enum.model_based": "model leren",
        "enum.self_directed": "zelfgestuurd",
        "enum.collaborative": "samenwerkend",
        "enum.reflective": "reflectief",
        "enum.thematic_context": "thematische context",
        "enum.material_rich": "materiaalrijk",
        "enum.self_starting": "self-starting",
        "enum.self_explaining": "self-explaining",
        "enum.proactive_invitation": "proactieve uitnodiging",
        "enum.safe_try_retry": "veilig proberen en opnieuw proberen",
        "enum.choice_autonomy": "keuze en autonomie",
        "enum.direct_feedback": "directe feedback",
        "enum.productive_barrier": "productieve barriere",
        "enum.visible_success": "zichtbaar succes",
        "enum.non_invasive_observation": "non-invasieve observatie",
        "enum.minimum_engine_input": "minimale engine-input",
        "enum.rich_simulation_context": "rijke simulatiecontext",
        "enum.multiple_profile_routes": "meerdere profielroutes",
        "enum.research_material": "onderzoeksmateriaal",
        "enum.language_material": "taalmateriaal",
        "enum.creative_material": "creatief materiaal",
        "enum.decoration_material": "decoratiemateriaal",
        "enum.math_material": "rekenmateriaal",
        "enum.physical_tool": "fysiek gereedschap",
        "enum.digital_canvas": "digitaal canvas",
        "enum.portfolio_canvas": "portfolio-canvas",
        "enum.role_card": "rolkaart",
        "enum.mission_card": "missiekaart",
        "enum.story_object": "verhaalobject",
        "enum.construction_block": "bouwblok",
        "enum.sensor_object": "sensorobject",
        "enum.feedback_display": "feedbackdisplay",
        "enum.success_artifact": "succesartefact",
        "enum.living_room": "huiskamer",
        "enum.arena": "arena",
        "enum.laboratory": "laboratorium",
        "enum.stage": "podium",
        "enum.goal_clarity": "doelhelderheid",
        "enum.intrinsic_motivation": "intrinsieke motivatie",
        "enum.prior_knowledge_connection": "aansluiting voorkennis",
        "enum.practice_opportunity": "oefenkans",
        "enum.process_support": "processteun",
        "enum.assessment_evidence": "bewijs van beheersing",
        "enum.reflection": "reflectie",
        "enum.differentiation": "differentiatie",
        "enum.formativity": "formatief volgen",
        "enum.real_world_relevance": "echtewereldrelevantie",
        "enum.creativity": "creativiteit",
        "enum.basic_skills_integrated": "basisvaardigheden geintegreerd",
        "enum.citizenship_integrated": "burgerschap geintegreerd",
        "enum.teacher_workload_reduction": "werkdrukverlaging",
        "enum.accessibility": "toegankelijkheid",
        "enum.social_safety": "sociale veiligheid",
        "enum.container": "container / box",
        "enum.workspace": "werkplek",
        "enum.tool": "gereedschap",
        "enum.material": "materiaal",
        "enum.instruction_card": "instructiekaart",
        "enum.choice_station": "keuzestation",
        "enum.resource": "resource",
        "enum.building_block": "bouwblok",
        "enum.puzzle_lock": "puzzelslot",
        "enum.barrier_mechanism": "barrieremechanisme",
        "enum.feedback_signal": "feedbacksignaal",
        "enum.progress_indicator": "voortgangsindicator",
        "enum.success_gate": "succespoort",
        "enum.reward_artifact": "beloningsartefact",
        "enum.reflection_prompt": "reflectieprompt",
        "enum.portfolio_surface": "portfolio-oppervlak",
        "enum.collaboration_surface": "samenwerkingsoppervlak",
        "enum.sensor": "sensor",
        "enum.simulation_state": "simulatietoestand",
        "enum.look": "kijken",
        "enum.pick_up": "oppakken",
        "enum.choose": "kiezen",
        "enum.sort": "sorteren",
        "enum.combine": "combineren",
        "enum.build": "bouwen",
        "enum.test": "testen",
        "enum.measure": "meten",
        "enum.compare": "vergelijken",
        "enum.transform": "transformeren",
        "enum.role_play": "rollenspel",
        "enum.negotiate": "onderhandelen",
        "enum.explain": "uitleggen",
        "enum.present": "presenteren",
        "enum.reflect": "reflecteren",
        "enum.retry": "opnieuw proberen",
        "enum.unlock": "ontgrendelen",
        "enum.collect": "verzamelen",
        "enum.record": "vastleggen",
        "enum.share": "delen",
        "enum.auditory": "auditief",
        "enum.tactile": "tactiel",
        "enum.movement": "beweging",
        "enum.state_change": "toestandsverandering",
        "enum.score": "score",
        "enum.unlock": "ontgrendeling",
        "enum.hint": "hint",
        "enum.peer_response": "peerreactie",
        "enum.facilitator_response": "begeleidersreactie",
        "enum.artifact_quality": "kwaliteit van artefact",
        "enum.system_log": "systeemlog",
        "enum.none": "geen",
        "enum.conceptual_puzzle": "conceptuele puzzel",
        "enum.material_misfit": "materiaal-misfit",
        "enum.sequence_error": "volgordefout",
        "enum.resource_shortage": "resourcetekort",
        "enum.time_pressure": "tijdsdruk",
        "enum.role_conflict": "rolconflict",
        "enum.social_threshold": "sociale drempel",
        "enum.technical_lock": "technische lock",
        "enum.quality_check": "kwaliteitscheck",
        "enum.ambiguity": "ambiguiteit",
        "enum.choice_overload": "keuze-overload",
        "enum.rfid_nfc": "RFID/NFC",
        "enum.button": "knop",
        "enum.switch": "schakelaar",
        "enum.magnetic_contact": "magneetcontact",
        "enum.load_cell": "load-cell",
        "enum.camera": "camera",
        "enum.microphone": "microfoon",
        "enum.accelerometer": "accelerometer",
        "enum.touchscreen": "touchscreen",
        "enum.software_log": "softwarelog",
        "enum.manual_observation": "handmatige observatie",
        "enum.qr_scan": "QR-scan",
        "enum.mission_game": "missiegame",
        "enum.simulation": "simulatie",
        "enum.adventure": "adventure",
        "enum.sandbox": "sandbox",
        "enum.puzzle": "puzzel",
        "enum.role_play": "rollenspel",
        "enum.strategy": "strategie",
        "enum.construction": "constructie",
        "enum.escape_room": "escape room",
        "enum.quest": "quest",
        "enum.collecting": "verzamelen",
        "enum.cooperative": "cooperatief",
        "enum.competitive": "competitief",
        "enum.creative_tool": "creatieve tool",
        "enum.choice": "keuze",
        "enum.resource_management": "resourcemanagement",
        "enum.collection": "collectie",
        "enum.construction": "constructie",
        "enum.matching": "matchen",
        "enum.sequencing": "volgorde maken",
        "enum.trading": "handelen",
        "enum.negotiation": "onderhandelen",
        "enum.role_assignment": "rollen verdelen",
        "enum.turn_taking": "beurten",
        "enum.timer": "timer",
        "enum.unlocking": "unlocking",
        "enum.leveling": "levels",
        "enum.scoring": "scoring",
        "enum.quest_completion": "quest afronden",
        "enum.crafting": "crafting",
        "enum.experimentation": "experimenteren",
        "enum.risk_reward": "risico-beloning",
        "enum.cooperation": "samenwerking",
        "enum.competition": "competitie",
        "enum.exploration": "verkenning",
        "enum.optimization": "optimalisatie",
        "enum.trial_and_error": "trial-and-error",
        "enum.strategy_shift": "strategiewissel",
        "enum.emergent_order": "emergente orde",
        "enum.escalating_challenge": "oplopende uitdaging",
        "enum.recovery_loop": "herstelloop",
        "enum.social_proof": "sociaal bewijs",
        "enum.creative_expression": "creatieve expressie",
        "enum.mastery_loop": "meesterschapsloop",
        "enum.sensation": "sensatie",
        "enum.fantasy": "fantasie",
        "enum.challenge": "uitdaging",
        "enum.fellowship": "verbondenheid",
        "enum.discovery": "ontdekking",
        "enum.expression": "expressie",
        "enum.submission": "overgave",
        "enum.meaning": "betekenis",
        "enum.competence": "competentie",
        "enum.autonomy": "autonomie",
        "enum.relatedness": "verbondenheid",
        "enum.levels": "levels",
        "enum.badges": "badges",
        "enum.unlockable_tools": "vrijspeelbare tools",
        "enum.unlockable_areas": "vrijspeelbare gebieden",
        "enum.skill_tree": "skill tree",
        "enum.portfolio_growth": "portfolio-groei",
        "enum.resource_growth": "resource-groei",
        "enum.difficulty_ramp": "oplopende moeilijkheid",
        "enum.narrative_chapters": "verhaalhoofdstukken"
      }
    }
  };
})();
